'use strict';
// test/runbook.test.js: tests for bridge/runbook.js. Builds small JSONL
// transcripts in a temp dir; never touches ~/.claude.

const { test, describe, before, after } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { build, toMarkdown, toHtml, _test } = require('../bridge/runbook.js');

const CWD = 'D:\\work\\helpdesk';
const T0 = Date.parse('2026-10-06T14:00:00.000Z');
let dir;
let clock = 0;
let ids = 0;

function base(type, extra) {
  clock += 1000;
  return { type, timestamp: new Date(T0 + clock).toISOString(), cwd: CWD, gitBranch: 'fix/vpn', sessionId: 's-1', ...extra };
}
const prompt = (text, extra = {}) => base('user', { message: { role: 'user', content: text }, ...extra });
const say = (text) => base('assistant', { message: { role: 'assistant', content: [{ type: 'text', text }] } });
function call(name, input) {
  const id = 'toolu_' + (++ids);
  return { id, line: base('assistant', { message: { role: 'assistant', content: [{ type: 'tool_use', id, name, input }] } }) };
}
function result(id, content, isError, toolUseResult) {
  const block = { type: 'tool_result', tool_use_id: id, content };
  if (isError) block.is_error = true;
  return base('user', { message: { role: 'user', content: [block] }, ...(toolUseResult ? { toolUseResult } : {}) });
}
/** A tool call plus its result, as two lines. */
function tool(name, input, opts = {}) {
  const c = call(name, input);
  return [c.line, result(c.id, opts.out || 'ok', !!opts.error, opts.tur)];
}
const bash = (command, description, opts) => tool('Bash', description ? { command, description } : { command }, opts);
const ps = (command, description, opts) => tool('PowerShell', description ? { command, description } : { command }, opts);

function write(name, lines) {
  const f = path.join(dir, name);
  fs.writeFileSync(f, lines.flat().map((l) => (typeof l === 'string' ? l : JSON.stringify(l))).join('\n') + '\n');
  return f;
}

function sampleSession() {
  clock = 0;
  return [
    { type: 'queue-operation', operation: 'enqueue' },
    prompt('<system-reminder>project rules here</system-reminder>'),
    prompt('<command-name>/clear</command-name>'),
    prompt('Caveat: The messages below were generated by the user while running local commands.', { isMeta: true }),
    prompt('Users on the 3rd floor cannot reach the VPN gateway — fix it and write it up.\nThey get error 809.'),
    say('Looking at the adapter first.'),
    ps('Get-NetAdapter | Select-Object Name, Status', 'Show network adapters'),
    bash('ls -la /etc/ipsec.d', 'List the ipsec config dir'),
    bash('grep -r nothing-here /etc', 'Search for the old key', { error: true, out: 'Exit code 1' }),
    bash('cat /var/log/vpn.log | tail -n 50'),
    ps('git status'),
    ps('git status'),
    // failed, then succeeded with the same command
    ps('Set-ItemProperty -Path HKLM:\\SYSTEM\\CurrentControlSet\\Services\\PolicyAgent -Name AssumeUDPEncapsulationContextOnSendRule -Value 2', 'Allow NAT-T for the VPN client', { error: true, out: 'Access is denied' }),
    ps('Set-ItemProperty -Path HKLM:\\SYSTEM\\CurrentControlSet\\Services\\PolicyAgent -Name AssumeUDPEncapsulationContextOnSendRule -Value 2', 'Allow NAT-T for the VPN client'),
    tool('Edit', { file_path: CWD + '\\config\\vpn.conf', old_string: 'a', new_string: 'b' }),
    tool('Edit', { file_path: CWD + '\\config\\vpn.conf', old_string: 'c', new_string: 'd' }),
    tool('MultiEdit', { file_path: CWD + '\\scripts\\fix.ps1', edits: [{}, {}, {}] }),
    tool('Write', { file_path: CWD + '\\docs\\vpn-fix.md', content: '# notes' }, { tur: { type: 'create', filePath: CWD + '\\docs\\vpn-fix.md' } }),
    tool('Write', { file_path: 'f:\\Temp\\claude\\x\\scratchpad\\probe.py', content: 'print(1)' }),
    tool('Edit', { file_path: CWD + '\\broken.txt', old_string: 'x', new_string: 'y' }, { error: true, out: 'String to replace not found' }),
    ps('Restart-Service PolicyAgent -Force', 'Restart the IPsec policy agent.'),
    bash('cd "D:\\work\\helpdesk" && npm run build', 'Build the helper'),
    bash('rm -rf /tmp/nothing', 'Remove the stale cache', { error: true, out: 'Exit code 1\nrm: permission denied' }),
    bash('node --test', 'Run the test suite', { out: 'pass 12\nfail 0' }),
    bash('node --test', 'Run the test suite', { out: 'pass 12\nfail 0' }),
    bash('curl -s http://localhost:3131/health', 'Check the health endpoint'),
    bash('echo "<script>alert(1)</script>" > out.txt', 'Write the marker file'),
    say('Done. **NAT-T** is allowed and the agent restarted — users can connect again.\n\n## Details\nRegistry key set to `2`.'),
  ];
}

before(() => { dir = fs.mkdtempSync(path.join(os.tmpdir(), 'gander-runbook-')); });
after(() => { try { fs.rmSync(dir, { recursive: true, force: true }); } catch (_) { /* ignore */ } });

describe('build', () => {
  test('steps: successful changing commands only, in order, description as title', async () => {
    const rb = await build(write('a.jsonl', sampleSession()));
    assert.deepEqual(rb.steps.map((s) => s.title), [
      'Allow NAT-T for the VPN client',
      'Restart the IPsec policy agent',
      'Build the helper',
      'Write the marker file',
    ]);
    assert.deepEqual(rb.steps.map((s) => s.n), [1, 2, 3, 4]);
    assert.deepEqual(rb.steps.map((s) => s.shell), ['powershell', 'powershell', 'bash', 'bash']);
    // the leading cd into the session cwd is dropped from the command
    assert.equal(rb.steps[2].command, 'npm run build');
    assert.ok(rb.steps[0].at && !Number.isNaN(Date.parse(rb.steps[0].at)));
    for (const s of rb.steps) {
      assert.ok(!/git status|ls -la|Get-NetAdapter|grep|rm -rf|node --test/.test(s.command), s.command);
    }
  });

  test('failed then succeeded shows once; failures are counted', async () => {
    const rb = await build(write('b.jsonl', sampleSession()));
    assert.equal(rb.steps.filter((s) => /Set-ItemProperty/.test(s.command)).length, 1);
    // Set-ItemProperty failure + rm failure; the empty grep is not an "attempt"
    assert.equal(rb.failedAttempts, 2);
    assert.equal(rb.truncated, false);
  });

  test('checks: read-only commands, deduped, passing tests marked', async () => {
    const rb = await build(write('c.jsonl', sampleSession()));
    const titles = rb.checks.map((c) => c.title);
    assert.ok(titles.includes('Show network adapters'));
    assert.ok(titles.includes('List the ipsec config dir'));
    assert.ok(titles.includes('Check the health endpoint'));
    assert.equal(rb.checks.filter((c) => c.command === 'git status').length, 1);
    const tests = rb.checks.filter((c) => c.passed);
    assert.equal(tests.length, 1);
    assert.equal(tests[0].title, 'Run the test suite');
    assert.ok(!titles.includes('Search for the old key'), 'a failed check is not verification');
    // no description: a short form of the command
    assert.ok(rb.checks.some((c) => c.title === 'cat /var/log/vpn.log | tail -n 50'));
    assert.ok(rb.checks.length <= 15);
  });

  test('checks are capped at 15', async () => {
    clock = 0;
    const lines = [prompt('look around')];
    for (let i = 0; i < 30; i++) lines.push(bash('cat file' + i + '.txt', 'Read file ' + i));
    lines.push(bash('npm test', 'Run tests'));
    const rb = await build(write('cap.jsonl', lines));
    assert.equal(rb.checks.length, 15);
    assert.ok(rb.checks.some((c) => c.passed), 'passing tests are kept first');
    assert.ok(rb.checks.some((c) => c.title === 'Read file 29'), 'the latest checks are kept');
  });

  test('filesChanged aggregates edits, relative paths, created marked, scratch skipped', async () => {
    const rb = await build(write('d.jsonl', sampleSession()));
    assert.deepEqual(rb.filesChanged, [
      { file: 'config/vpn.conf', edits: 2, created: false },
      { file: 'scripts/fix.ps1', edits: 3, created: false },
      { file: 'docs/vpn-fix.md', edits: 1, created: true },
    ]);
  });

  test('meta, goal skips harness tags, outcome is the last text', async () => {
    const rb = await build(write('e.jsonl', sampleSession()));
    assert.equal(rb.project, 'helpdesk');
    assert.equal(rb.cwd, CWD);
    assert.equal(rb.branch, 'fix/vpn');
    assert.ok(rb.goal.startsWith('Users on the 3rd floor'));
    assert.ok(rb.goal.includes('error 809'));
    assert.ok(!rb.goal.includes('\u2014'));
    assert.ok(rb.title.startsWith('Users on the 3rd floor'));
    assert.ok(!rb.title.includes('error 809'), 'title is the first line only');
    assert.ok(rb.title.length <= 100);
    assert.ok(rb.outcome.startsWith('Done.'));
    assert.ok(rb.startedAt < rb.endedAt);
    assert.equal(rb.empty, false);
  });

  test('opts.title overrides; since/until window', async () => {
    const f = write('f.jsonl', sampleSession());
    const rb = await build(f, { title: 'VPN 809 fix' });
    assert.equal(rb.title, 'VPN 809 fix');
    const late = await build(f, { since: new Date(T0 + 1000 * 1000).toISOString() });
    assert.equal(late.steps.length, 0);
    assert.equal(late.empty, true);
  });

  test('compaction summary is not the goal; work after it still counts', async () => {
    clock = 0;
    const lines = [
      { type: 'system', subtype: 'compact_boundary', content: 'Conversation compacted' },
      prompt('This session is being continued from a previous conversation. Summary: lots of stuff', { isCompactSummary: true }),
      prompt('Now rotate the service account password'),
      ps('Set-ADAccountPassword svc-backup -Reset', 'Reset the service account password'),
    ];
    const rb = await build(write('g.jsonl', lines));
    assert.equal(rb.goal, 'Now rotate the service account password');
    assert.equal(rb.steps.length, 1);
    assert.equal(rb.steps[0].title, 'Reset the service account password');
  });

  test('sidechain lines are ignored', async () => {
    clock = 0;
    const [u, r] = bash('npm install left-pad', 'Install a dep');
    u.isSidechain = true; r.isSidechain = true;
    const rb = await build(write('h.jsonl', [prompt('hi'), u, r]));
    assert.equal(rb.steps.length, 0);
  });

  test('tool-call cap truncates', async () => {
    clock = 0;
    const lines = [prompt('do a lot')];
    for (let i = 0; i < _test.MAX_TOOL_CALLS + 5; i++) lines.push(bash('touch f' + i, 'Touch ' + i));
    lines.push(say('All done.'));
    const rb = await build(write('big.jsonl', lines));
    assert.equal(rb.truncated, true);
    assert.equal(rb.steps.length, _test.MAX_TOOL_CALLS);
    assert.equal(rb.outcome, 'All done.');
    assert.match(toMarkdown(rb), /stops after the first 2000 tool calls/);
  });

  test('no-description steps get readable titles; scratch scripts get a note; chained tests become checks', async () => {
    clock = 0;
    const lines = [
      prompt('fix the queue'),
      bash('PYTHONIOENCODING=utf-8 F:/venv/Scripts/python.exe "f:/Temp/claude/x/scratchpad/patch_q.py" && F:/venv/Scripts/python.exe -m pytest -q 2>&1 | tail -3'),
      bash("python - <<'PY'\nfrom pathlib import Path\np = Path(\"tests/test_q.py\")\np.write_text('x')\nPY\nnpm run build"),
      bash("python - <<'PY'\nimport json\nprint(json.load(open('state.json')))\nPY"),
      bash('git add -A && git commit -qm "Start now lifts a pause (button reads Resume); quieter log" && git log --oneline -1'),
      ps("Get-CimInstance Win32_Process | Where-Object { $_.CommandLine -match 'uvicorn' } | ForEach-Object { Stop-Process -Id $_.ProcessId -Force }; Start-Process -FilePath C:\\py\\python.exe -ArgumentList '-m','uvicorn'"),
      bash("cd 'd:\\Files\\x\\.claude\\memory' && python - <<'PY'\nopen('a.md','a').write('x')\nPY", 'Append a lesson to memory'),
      tool('Write', { file_path: 'd:\\Files\\x\\.claude\\memory\\note.md', content: 'x' }),
    ];
    const rb = await build(write('titles.jsonl', lines));
    assert.deepEqual(rb.steps.map((s) => s.title), [
      'python patch_q.py',
      'python: edit tests/test_q.py + npm run build',
      'git commit "Start now lifts a pause"',
      'Stop-Process + Start-Process python',
    ]);
    assert.match(rb.steps[0].note, /patch_q\.py from the original session's scratch folder/);
    assert.ok(rb.checks.some((c) => c.passed && c.title === 'python -m pytest'), 'pytest chained after a change is a passing check');
    assert.ok(rb.checks.some((c) => c.title === 'python: read state.json'), 'a read-only inline script is a check');
    assert.deepEqual(rb.filesChanged, [], "Claude's memory files are not part of the fix");
    const md = toMarkdown(rb);
    assert.match(md, /_Note: Runs patch_q\.py/);
  });

  test('IDE context blocks are stripped; a resumed transcript falls back to last-prompt', async () => {
    clock = 0;
    const ide = await build(write('ide.jsonl', [
      base('user', { message: { role: 'user', content: [{ type: 'text', text: '<ide_opened_file>The user opened a.js</ide_opened_file>' }, { type: 'text', text: 'why does the printer queue jam?' }] } }),
    ]));
    assert.equal(ide.goal, 'why does the printer queue jam?');
    assert.equal(ide.title, 'Why does the printer queue jam?');
    clock = 0;
    const resumed = await build(write('resumed.jsonl', [
      { type: 'last-prompt', lastPrompt: 'Reset the kiosk profile on floor 2', sessionId: 's-1' },
      ...ps('Remove-Item C:\\Users\\kiosk\\AppData\\Local\\Temp\\x -Recurse', 'Clear the kiosk cache'),
    ]));
    assert.equal(resumed.goal, 'Reset the kiosk profile on floor 2');
    assert.equal(resumed.steps.length, 1);
  });

  test('long outcomes are cut at a paragraph, not mid-word', async () => {
    clock = 0;
    const para = 'This sentence explains what changed in some detail. '.repeat(6).trim();
    const text = Array.from({ length: 8 }, () => para).join('\n\n');
    const rb = await build(write('long.jsonl', [prompt('go'), say(text)]));
    assert.ok(rb.outcome.length <= 1500);
    assert.ok(rb.outcome.endsWith('detail.\n\n…'), JSON.stringify(rb.outcome.slice(-30)));
  });

  test('missing, empty and junk transcripts do not throw', async () => {
    for (const f of [path.join(dir, 'nope.jsonl'), write('empty.jsonl', []), write('junk.jsonl', ['{not json', '"x"', 'null'])]) {
      const rb = await build(f);
      assert.equal(rb.empty, true);
      assert.deepEqual(rb.steps, []);
      assert.match(toMarkdown(rb), /Nothing to hand off yet/);
      assert.match(toHtml(rb), /Nothing to hand off yet/);
    }
    const rb = await build('');
    assert.equal(rb.empty, true);
    assert.match(toMarkdown(undefined), /Nothing to hand off yet/);
  });
});

describe('classifyCommand', () => {
  const c = _test.classifyCommand;
  test('read-only', () => {
    for (const cmd of ['ls -la', 'dir C:\\', 'cat a | grep b', 'Get-ChildItem -Recurse | Select-String foo', 'git log --oneline -5',
      'git -C D:\\x status', 'git branch -a', 'curl -s http://x/health', 'curl -sSL -X GET http://x', 'node --check a.js', 'echo hi 2>&1',
      'findstr /s foo *.txt', 'Get-Content a.txt -Tail 5', 'which node', 'type a.txt > NUL', 'grep x a 2>/dev/null', 'Test-Path C:\\x',
      'cd D:\\x && git diff', '$r = Get-Service spooler; $r.Status', 'npm ls', 'sc query spooler', 'reg query HKLM\\Software\\X']) {
      assert.equal(c(cmd), 'read', cmd);
    }
  });
  test('changing', () => {
    for (const cmd of ['npm install', 'echo x > a.txt', 'git commit -m "x"', 'git branch new-one', 'curl -X POST http://x', 'curl -d a=1 http://x',
      'curl -sSo out.bin http://x', 'Restart-Service x', 'Get-Content a | Set-Content b', 'Remove-Item -Recurse x', 'sed -i s/a/b/ f',
      'find . -name "*.tmp" -delete', 'python fix.py', 'cat <<EOF > a.txt\nhello\nEOF', 'Invoke-RestMethod -Method Post http://x',
      'git checkout -b x', 'sc config spooler start= auto', 'net user bob /add']) {
      assert.equal(c(cmd), 'change', cmd);
    }
  });
  test('tests and noise', () => {
    for (const cmd of ['npm test', 'node --test test/a.test.js', 'pytest -q', 'python -m pytest', 'go test ./...', 'dotnet test', 'npx vitest run']) {
      assert.equal(c(cmd), 'test', cmd);
    }
    assert.equal(c('npm run build && npm test'), 'change');
    assert.equal(c('sleep 5'), 'neutral');
    assert.equal(c('cd D:\\x'), 'neutral');
  });
  test('inline scripts and heredocs', () => {
    assert.equal(c('python -c "import json; print(json.load(open(\'a.json\')))"'), 'read');
    assert.equal(c('python -c "open(\'a.txt\', \'w\').write(\'x\')"'), 'change');
    assert.equal(c("python - <<'PY'\nprint(1)\nPY"), 'read');
    assert.equal(c("python - <<'PY'\nimport shutil\nshutil.rmtree('x')\nPY"), 'change');
    assert.equal(c("python - <<'PY'\nprint(1)\nPY\nrm -rf build"), 'change', 'commands after the heredoc still count');
    assert.equal(c('node -e "console.log(require(\'./package.json\').version)"'), 'read');
    assert.equal(c('node -e "require(\'fs\').writeFileSync(\'a\', \'b\')"'), 'change');
    assert.equal(c("find . \\( -name '*.png' -o -name '*.jpg' \\) -print"), 'read');
    assert.equal(c("try { (Get-Command yt-dlp -ErrorAction Stop).Source } catch { \"not on PATH\" }"), 'read');
  });
  test('quoted operators do not split', () => {
    assert.equal(c('grep "a > b; rm -rf /" file'), 'read');
    assert.equal(c("echo 'x | Set-Content y'"), 'read');
  });
  test('description prefixes', () => {
    assert.equal(_test.descIsCheck('Check the service state'), true);
    assert.equal(_test.descIsCheck('Inspect logs'), true);
    assert.equal(_test.descIsCheck('Check out the release branch'), false);
    assert.equal(_test.descIsCheck('Restart the service'), false);
  });
});

describe('toMarkdown', () => {
  test('structure, language tags, notes, no em-dash', async () => {
    const rb = await build(write('m.jsonl', sampleSession()));
    const md = toMarkdown(rb);
    const lines = md.split('\n');
    assert.ok(lines[0].startsWith('# Users on the 3rd floor'));
    assert.match(md, /helpdesk · fix\/vpn · \d{4}-\d{2}-\d{2} · /);
    const order = ['## Goal', '## Steps', '## Files changed', '## How it was verified', '## Outcome'].map((h) => md.indexOf('\n' + h + '\n'));
    assert.ok(order.every((i) => i > 0), 'all sections present');
    assert.deepEqual(order, order.slice().sort((a, b) => a - b), 'sections in order');
    assert.match(md, /1\. \*\*Allow NAT-T for the VPN client\*\*\n\n {3}```powershell\n {3}Set-ItemProperty/);
    assert.match(md, /3\. \*\*Build the helper\*\*\n\n {3}```bash\n {3}npm run build\n {3}```/);
    assert.match(md, /`config\/vpn.conf`: 2 edits/);
    assert.match(md, /`docs\/vpn-fix.md`: created/);
    assert.match(md, /\*\*Passed:\*\* Run the test suite/);
    assert.match(md, /2 attempts that failed along the way are left out\./);
    assert.ok(!md.includes('\u2014'), 'no em-dash');
    // Claude's own heading is demoted below ours
    assert.ok(!/^## Details/m.test(md));
    assert.match(md, /\*\*Details\*\*/);
  });

  test('fences survive backticks in commands', () => {
    const md = toMarkdown({ title: 'x', steps: [{ n: 1, title: 'Weird', command: 'echo ```nested```', shell: 'bash' }], filesChanged: [], checks: [] });
    assert.match(md, /````bash\n {3}echo ```nested```\n {3}````/);
  });
});

describe('toHtml', () => {
  test('escapes, self-contained, copy + download controls', async () => {
    const rb = await build(write('h2.jsonl', sampleSession()));
    rb.steps.push({ n: 99, title: '</script><script>alert(2)</script>', command: '</script><img src=x onerror=alert(3)>', shell: 'bash', at: null });
    const html = toHtml(rb);
    assert.ok(html.startsWith('<!doctype html>'));
    assert.match(html, /Content-Security-Policy" content="default-src 'none'/);
    assert.ok(!html.includes('<script>alert'), 'raw script tag never reaches the page');
    assert.ok(!html.includes('<img src=x'), 'raw img never reaches the page');
    assert.ok(html.includes('&lt;script&gt;alert(1)&lt;/script&gt;'));
    // exactly two script elements: the JSON data block and the client code
    assert.equal((html.match(/<script\b/g) || []).length, 2);
    assert.ok(!/(?:src|href)\s*=\s*["']?\s*(?:https?:)?\/\//i.test(html), 'no external src/href');
    assert.ok(!/url\(\s*["']?\s*(?:https?:)?\/\//i.test(html), 'no external css url()');
    assert.ok(!/@import/i.test(html));
    assert.ok(!/<link\b/i.test(html));
    assert.match(html, /Copy as Markdown/);
    assert.match(html, /Download \.md/);
    assert.match(html, /data-file="runbook-users-on-the-3rd-floor[\w-]*\.md"/);
    assert.match(html, /data-act="copy-code"/);
    assert.match(html, /@media print/);
    assert.match(html, /prefers-color-scheme:dark/);
    assert.ok(!html.includes('\u2014'), 'no em-dash');
    // the embedded markdown parses back to exactly toMarkdown(rb)
    const m = /<script type="application\/json" id="runbook-md">([\s\S]*?)<\/script>/.exec(html);
    assert.ok(m);
    assert.equal(JSON.parse(m[1]), toMarkdown(rb));
  });

  test('empty runbook renders the hand-off message', () => {
    const html = toHtml({});
    assert.match(html, /Nothing to hand off yet/);
  });
});
